# Generated by Django 4.1.2 on 2022-10-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_configuracion_subtitulo_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_desarrollador', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
                ('anno_fundacion', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_juego', models.CharField(max_length=30)),
                ('desarrollador', models.CharField(max_length=30)),
                ('genero', models.CharField(default='', max_length=30)),
                ('cantidad_jugadores', models.CharField(default='', max_length=30)),
                ('reseña', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('sub_titulo', models.CharField(max_length=60)),
                ('contenido', models.CharField(max_length=200)),
            ],
        ),
    ]
