# Generated by Django 4.1.2 on 2022-10-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_desarrollador_juego_noticias'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='fecha',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='contenido',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='sub_titulo',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(default='', max_length=60),
        ),
    ]
