# Generated by Django 4.1.2 on 2022-10-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_desarrollador_juego_noticias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='reseña',
            field=models.CharField(default='', max_length=200),
        ),
    ]
