# Generated by Django 4.1.2 on 2022-10-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_noticias_fecha_alter_noticias_contenido_and_more'),
        ('blog', '0007_noticias_fecha'),
    ]

    operations = [
    ]
