# Generated by Django 4.1.2 on 2022-10-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_merge_20221022_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='reseña',
            new_name='resena',
        ),
        migrations.RemoveField(
            model_name='noticias',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='construido_por',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='nombre_blog',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='desarrollador',
            name='nombre_desarrollador',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='desarrollador',
            name='pais',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='juego',
            name='desarrollador',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='juego',
            name='nombre_juego',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='contenido',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='sub_titulo',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=60),
        ),
    ]
