# Generated by Django 4.1.2 on 2022-10-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_reseña_juego_resena_remove_noticias_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='fecha',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
