# Generated by Django 4.1.2 on 2022-10-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_noticias_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='resena',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='contenido',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='fecha',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='sub_titulo',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(default='', max_length=60),
        ),
    ]
