# Generated by Django 4.1.2 on 2022-11-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_juego_resena_alter_noticias_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='contenido',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='sub_titulo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
