# Generated by Django 4.1.2 on 2022-11-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_noticias_contenido_alter_noticias_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias'),
        ),
    ]
