# Generated by Django 4.1.2 on 2022-11-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_noticias_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrollador',
            name='nombre_desarrollador',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='juego',
            name='desarrollador',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='juego',
            name='genero',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='juego',
            name='nombre_juego',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='juego',
            name='resena',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='contenido',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
